name:                        state
on:                          [issues, pull_request]
jobs:
  state:
    runs-on:                 ubuntu-latest
    steps:
      - name:                Reactions
        uses:                bubkoo/auto-comment@v1
        with:
          GITHUB_TOKEN:      ${{ secrets.GITHUB_TOKEN }}
          issuesOpened:      >
            Hey @{{ author }},<br /><br />
            This repo is not currenlty maintained.<br />
            Please refer to #244 for more info on **alternatives** or how you can help.<br /><br />
            _For **crashes alone**, please reply under this by mentioning `@sbertix`._<br />
            _If no exception is ever raised in your code and the feature is simply not behaving as expected or as it used to, this will likely not be fixed at the moment._<br />
            _Your issue, however, **will not be closed**, in hopes of **SwiftyInsta** being maintained again._
          pullRequestOpened: >
            Hey @{{ author }},<br /><br />
            This repo is not currently maintained.<br />
            Please refer to #244 for more info on **alternatives** or how you can help.<br /><br />
            Once you're staisfied with your PR, please request a review from `@sbertix`.<br /><br />
            _Reviews for **crash fixes** will always be considered._
